# Generated by Django 5.1.2 on 2024-10-22 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_restoran', models.CharField(max_length=255)),
                ('lokasi', models.CharField(max_length=255)),
                ('jenis_suasana', models.CharField(max_length=255)),
                ('keramaian_restoran', models.IntegerField()),
                ('jenis_penyajian', models.CharField(max_length=255)),
                ('ayce_atau_alacarte', models.CharField(max_length=255)),
                ('harga_rata_rata_makanan', models.IntegerField()),
                ('gambar', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_menu', models.CharField(max_length=255)),
                ('cluster', models.CharField(max_length=255)),
                ('harga', models.IntegerField()),
                ('restoran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.restaurant')),
            ],
        ),
    ]
