# Generated by Django 5.1.2 on 2024-10-24 06:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_ratings_restaurant_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
