# Generated by Django 5.1.2 on 2024-10-24 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_alter_ratings_restaurant_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='restaurant_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ratings.restaurant'),
        ),
    ]
